const login=document.getElementById('login'),brand=login?.querySelector('.login-brand');
if(login&&brand){
  login.classList.add('login-reference','login-image-background');
  brand.hidden=true;
  const panel=document.getElementById('login-panel'),eyebrow=panel?.querySelector(':scope>.eyebrow'),heading=panel?.querySelector(':scope>h1');if(eyebrow)eyebrow.textContent='Welcome to';if(heading){heading.textContent='Nuvrion';heading.insertAdjacentHTML('afterend','<p class="login-signin-copy">Sign in to your account</p>')}
  const usernameField=document.querySelector('#login-form [name="username"]'),passwordField=document.querySelector('#login-form [name="password"]');if(usernameField)usernameField.placeholder='Username';if(passwordField)passwordField.placeholder='Password';
}
const loginForm=document.getElementById('login-form'),username=loginForm?.elements?.username,password=loginForm?.elements?.password,remember=document.getElementById('remember-login'),passwordToggle=document.getElementById('toggle-login-password'),rememberKey='nuvrion.login.rememberedUsername';
if(username&&remember){const saved=localStorage.getItem(rememberKey);if(saved){username.value=saved;remember.checked=true}loginForm.addEventListener('submit',()=>{if(remember.checked)localStorage.setItem(rememberKey,String(username.value??'').trim());else localStorage.removeItem(rememberKey)})}
globalThis.nuvrionStoreLoginCredential=async form=>{const userField=form?.elements?.username,passwordField=form?.elements?.password,rememberField=document.getElementById('remember-login');if(!rememberField?.checked||!userField?.value||!passwordField?.value)return false;if(typeof globalThis.PasswordCredential!=='function'||!navigator.credentials?.store)return false;try{await navigator.credentials.store(new PasswordCredential({id:String(userField.value).trim(),name:String(userField.value).trim(),password:String(passwordField.value)}));return true}catch{return false}};
if(password&&passwordToggle)passwordToggle.addEventListener('click',()=>{const showing=password.type==='text';password.type=showing?'password':'text';passwordToggle.setAttribute('aria-pressed',String(!showing));passwordToggle.setAttribute('aria-label',showing?'Show password':'Hide password');password.focus()});
