const login=document.getElementById('login'),brand=login?.querySelector('.login-brand');
if(login&&brand&&!login.querySelector('.login-intro')){
  const intro=document.createElement('div');intro.className='login-intro';brand.before(intro);intro.append(brand);
  intro.insertAdjacentHTML('beforeend','<div class="login-showcase"><p class="eyebrow">HYBRID OPERATIONS, ONE VIEW</p><h2>Operate your infrastructure with clarity.</h2><p>Monitor virtual machines, investigate health, and perform controlled lifecycle actions across every connected platform.</p><div class="login-capabilities"><div><span aria-hidden="true">◇</span><span><strong>Unified visibility</strong><small>Live inventory and performance insight</small></span></div><div><span aria-hidden="true">↗</span><span><strong>Controlled operations</strong><small>Provider-aware actions with verification</small></span></div><div><span aria-hidden="true">✓</span><span><strong>Auditable by design</strong><small>Every administrative action recorded</small></span></div></div></div>');
}
const loginForm=document.getElementById('login-form'),username=loginForm?.elements?.username,password=loginForm?.elements?.password,remember=document.getElementById('remember-login'),passwordToggle=document.getElementById('toggle-login-password'),rememberKey='nuvrion.login.rememberedUsername';
if(username&&remember){const saved=localStorage.getItem(rememberKey);if(saved){username.value=saved;remember.checked=true}loginForm.addEventListener('submit',()=>{if(remember.checked)localStorage.setItem(rememberKey,String(username.value??'').trim());else localStorage.removeItem(rememberKey)})}
globalThis.nuvrionStoreLoginCredential=async form=>{const userField=form?.elements?.username,passwordField=form?.elements?.password,rememberField=document.getElementById('remember-login');if(!rememberField?.checked||!userField?.value||!passwordField?.value)return false;if(typeof globalThis.PasswordCredential!=='function'||!navigator.credentials?.store)return false;try{await navigator.credentials.store(new PasswordCredential({id:String(userField.value).trim(),name:String(userField.value).trim(),password:String(passwordField.value)}));return true}catch{return false}};
if(password&&passwordToggle)passwordToggle.addEventListener('click',()=>{const showing=password.type==='text';password.type=showing?'password':'text';passwordToggle.setAttribute('aria-pressed',String(!showing));passwordToggle.setAttribute('aria-label',showing?'Show password':'Hide password');password.focus()});
