const csrf=()=>decodeURIComponent(document.cookie.split('; ').find(item=>item.startsWith('nuvrion_csrf='))?.split('=').slice(1).join('=')??'');
async function request(path,options={}){const response=await fetch(`/api/v1${path}`,{...options,headers:{...(options.headers??{}),...(options.method&&options.method!=='GET'?{'x-csrf-token':csrf()}:{})}});let value=null;try{value=await response.json()}catch{}if(!response.ok)throw new Error(value?.detail??`Request failed (${response.status})`);return value}

const sessions=document.getElementById('my-sessions');
if(sessions){
  sessions.insertAdjacentHTML('afterend','<button id="upgrade-center" type="button" data-permission="platform.manage" hidden><span aria-hidden="true">⇧</span><span><strong>Upgrade Center</strong><small>Verify and install a Nuvrion release</small></span></button>');
  document.body.insertAdjacentHTML('beforeend','<dialog id="upgrade-dialog" class="upgrade-dialog"><div class="sessions-panel"><header><div><p class="eyebrow">PLATFORM MAINTENANCE</p><h2>Upgrade Center</h2></div><button id="upgrade-close" type="button">Close</button></header><div class="upgrade-current"><span>Current platform version</span><strong id="upgrade-current-version">v—</strong><small id="upgrade-helper-state">Checking the RHEL9 upgrade helper…</small></div><label>Release bundle<input id="upgrade-file" type="file" accept=".zip,application/zip"></label><label>SHA-256 checksum<input id="upgrade-checksum" type="text" inputmode="text" maxlength="64" autocomplete="off" spellcheck="false" placeholder="Paste the 64-character release checksum"></label><div id="upgrade-progress" class="upgrade-progress" role="status"><span class="upgrade-status-dot" aria-hidden="true"></span><div><strong id="upgrade-status-title">Ready</strong><small id="upgrade-status-message">Select a Nuvrion release bundle.</small></div></div><p id="upgrade-error" class="form-error" role="alert"></p><div class="upgrade-actions"><button id="upgrade-verify" type="button">Verify release</button><span></span><button id="upgrade-install" type="button" class="primary" disabled>Install update</button></div><p class="session-policy">The platform creates a backup and restores the current version automatically if validation fails. The console may reconnect while the API restarts.</p></div></dialog>');
  const $=id=>document.getElementById(id),dialog=$('upgrade-dialog');let staged=null,poll=null,busy=false;
  function setBusy(value){busy=value;$('upgrade-file').disabled=value;$('upgrade-checksum').disabled=value;$('upgrade-verify').disabled=value;$('upgrade-install').disabled=value||!staged}
  function render(result){
    $('upgrade-current-version').textContent=`v${result.currentVersion??'—'}`;
    $('upgrade-helper-state').textContent=result.helperAvailable?'RHEL9 upgrade helper is ready.':'RHEL9 upgrade helper is not installed.';
    const status=result.status??{},state=status.state??'idle';$('upgrade-progress').dataset.state=state;$('upgrade-status-title').textContent=state[0]?.toUpperCase()+state.slice(1);$('upgrade-status-message').textContent=status.message??'No platform update is in progress.';
    staged=result.staged??staged;$('upgrade-install').disabled=busy||!result.helperAvailable||!staged||['queued','running'].includes(state);
    if(['succeeded','failed'].includes(state))setBusy(false);
  }
  async function refreshStatus(){try{render(await request('/platform/upgrade'))}catch(error){$('upgrade-status-title').textContent='Unavailable';$('upgrade-status-message').textContent=error.message}}
  $('upgrade-center').onclick=async()=>{document.querySelector('.account-menu').open=false;$('upgrade-error').textContent='';dialog.showModal();await refreshStatus();clearInterval(poll);poll=setInterval(refreshStatus,2000)};
  $('upgrade-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{clearInterval(poll);poll=null});
  $('upgrade-verify').onclick=async()=>{const file=$('upgrade-file').files[0],checksum=$('upgrade-checksum').value.trim();$('upgrade-error').textContent='';if(!file){$('upgrade-error').textContent='Select a Nuvrion release ZIP file.';return}setBusy(true);$('upgrade-progress').dataset.state='running';$('upgrade-status-title').textContent='Verifying';$('upgrade-status-message').textContent='Uploading and checking the release bundle…';try{staged=await request(`/platform/upgrade/upload?sha256=${encodeURIComponent(checksum)}`,{method:'POST',headers:{'content-type':'application/zip','x-nuvrion-file-name':file.name},body:file});$('upgrade-status-title').textContent='Verified';$('upgrade-status-message').textContent='Release verified and ready to install.'}catch(error){staged=null;$('upgrade-error').textContent=error.message;$('upgrade-status-title').textContent='Verification failed'}finally{setBusy(false);await refreshStatus()}};
  $('upgrade-install').onclick=async()=>{if(!staged||busy)return;if(!window.confirm('Install this verified Nuvrion update now? The console will reconnect while the API restarts.'))return;$('upgrade-error').textContent='';setBusy(true);try{await request('/platform/upgrade/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({uploadId:staged.uploadId})});$('upgrade-status-title').textContent='Queued';$('upgrade-status-message').textContent='The RHEL9 helper will begin the update shortly.';setTimeout(refreshStatus,500)}catch(error){$('upgrade-error').textContent=error.message;setBusy(false)}};
}
