const fs=require('node:fs');
const path=require('node:path');
const https=require('node:https');
const {execFile}=require('node:child_process');
const {createHmac,timingSafeEqual}=require('node:crypto');

const VERSION='0.1.0-lab.1';
const root=path.dirname(process.execPath);
const bootstrapPath=path.join(root,'bootstrap.json');
const identityPath=path.join(root,'identity.json');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const log=(event,detail={})=>process.stdout.write(`${JSON.stringify({time:new Date().toISOString(),event,...detail})}\n`);
const readJson=file=>JSON.parse(fs.readFileSync(file,'utf8').replace(/^\uFEFF/,''));
const writePrivate=(file,value)=>{fs.writeFileSync(file,JSON.stringify(value,null,2),{encoding:'utf8',mode:0o600});};
const run=(file,args,timeout=30000)=>new Promise((resolve,reject)=>execFile(file,args,{windowsHide:true,timeout},(error,stdout,stderr)=>error?reject(Object.assign(error,{detail:String(stderr||stdout).trim()})):resolve(String(stdout))));

function request(config,method,pathname,body,headers={}){
  const base=new URL(config.apiUrl),payload=body===undefined?null:Buffer.from(JSON.stringify(body));
  const ca=config.caCertificatePath?fs.readFileSync(config.caCertificatePath):undefined;
  return new Promise((resolve,reject)=>{const req=https.request({protocol:base.protocol,hostname:base.hostname,port:base.port||443,path:`${base.pathname.replace(/\/$/,'')}${pathname}`,method,ca,rejectUnauthorized:true,headers:{accept:'application/json',...(payload?{'content-type':'application/json','content-length':payload.length}:{}),...headers}},res=>{let raw='';res.setEncoding('utf8');res.on('data',chunk=>raw+=chunk);res.on('end',()=>{let parsed={};try{parsed=raw?JSON.parse(raw):{};}catch{return reject(new Error(`Invalid JSON response (${res.statusCode}).`));}if(res.statusCode<200||res.statusCode>=300)return reject(Object.assign(new Error(parsed.detail||`HTTP ${res.statusCode}`),{code:parsed.code,status:res.statusCode}));resolve(parsed);});});req.setTimeout(30000,()=>req.destroy(new Error('Nuvrion request timed out.')));req.on('error',reject);if(payload)req.write(payload);req.end();});
}
function walkVmx(rootPath,result,depth=0){if(depth>8||result.length>=2000||!fs.existsSync(rootPath))return;let entries=[];try{entries=fs.readdirSync(rootPath,{withFileTypes:true});}catch{return;}for(const entry of entries){const full=path.join(rootPath,entry.name);if(entry.isDirectory())walkVmx(full,result,depth+1);else if(entry.isFile()&&entry.name.toLowerCase().endsWith('.vmx'))result.push(full);}}
function vmxValue(text,key){const match=text.match(new RegExp(`^\\s*${key}\\s*=\\s*"([^"]*)"`,'mi'));return match?match[1]:null;}
async function inventory(config){const runningOutput=await run(config.vmrunPath,['list']),running=new Set(runningOutput.split(/\r?\n/).slice(1).map(x=>path.normalize(x.trim()).toLowerCase()).filter(Boolean)),files=[];for(const searchRoot of config.vmSearchRoots||[])walkVmx(searchRoot,files);return [...new Set(files.map(path.normalize))].map(file=>{let text='';try{text=fs.readFileSync(file,'utf8');}catch{}const memory=Number(vmxValue(text,'memsize')),cpu=Number(vmxValue(text,'numvcpus'));return {id:file,nativeId:file,name:vmxValue(text,'displayName')||path.basename(file,'.vmx'),path:file,powerState:running.has(file.toLowerCase())?'running':'stopped',guestOs:vmxValue(text,'guestOS'),vcpuCount:Number.isFinite(cpu)&&cpu>0?cpu:null,memoryBytes:Number.isFinite(memory)&&memory>0?memory*1048576:null,healthState:'unknown',observedAt:new Date().toISOString()};});}
function verify(secret,envelope){const expected=Buffer.from(createHmac('sha256',secret).update(JSON.stringify(envelope.payload)).digest('base64url')),actual=Buffer.from(String(envelope.signature||''));return expected.length===actual.length&&timingSafeEqual(expected,actual);}
async function execute(config,command){const {operation,targetId}=command.payload;if(!verify(config.identity.secret,command))throw Object.assign(new Error('Command signature is invalid.'),{code:'NUV_AGENT_COMMAND_TAMPERED'});if(Date.parse(command.payload.expiresAt)<=Date.now())throw Object.assign(new Error('Command expired.'),{code:'NUV_AGENT_COMMAND_EXPIRED'});const action={start:['start',targetId,'nogui'],stop:['stop',targetId,'soft'],restart:['reset',targetId,'soft']}[operation];if(!action)throw Object.assign(new Error('Unsupported operation.'),{code:'NUV_OPERATION_INVALID'});await run(config.vmrunPath,action,120000);return {code:'NUV_AGENT_OPERATION_COMPLETED',message:`VMware Workstation ${operation} completed.`,powerState:operation==='stop'?'stopped':'running'};}
async function main(){if(!fs.existsSync(bootstrapPath))throw new Error(`Missing ${bootstrapPath}`);const config=readJson(bootstrapPath);if(!config.apiUrl?.startsWith('https://'))throw new Error('apiUrl must use HTTPS.');if(!fs.existsSync(config.vmrunPath))throw new Error(`vmrun was not found at ${config.vmrunPath}`);if(!fs.existsSync(config.caCertificatePath))throw new Error(`CA certificate was not found at ${config.caCertificatePath}`);if(fs.existsSync(identityPath))config.identity=readJson(identityPath);else{const enrolled=await request(config,'POST','/api/v1/agents/enroll',{token:config.enrollmentToken,name:config.agentName||require('node:os').hostname(),version:VERSION});config.identity={agentId:enrolled.agentId,secret:enrolled.secret};writePrivate(identityPath,config.identity);delete config.enrollmentToken;writePrivate(bootstrapPath,config);log('agent.enrolled',{agentId:enrolled.agentId});}
  for(;;){try{const items=await inventory(config);await request(config,'POST',`/api/v1/agents/${config.identity.agentId}/heartbeat`,{version:VERSION,inventory:items},{'x-agent-secret':config.identity.secret});const commands=(await request(config,'GET',`/api/v1/agents/${config.identity.agentId}/commands`,undefined,{'x-agent-secret':config.identity.secret})).items||[];for(const command of commands){let status='completed',result;try{result=await execute(config,command);}catch(error){status='failed';result={code:error.code||'NUV_AGENT_EXECUTION_FAILED',message:error.message};}await request(config,'POST',`/api/v1/agents/${config.identity.agentId}/commands/${command.payload.commandId}/ack`,{status,result},{'x-agent-secret':config.identity.secret});}log('agent.heartbeat',{inventoryCount:items.length,commandCount:commands.length});}catch(error){log('agent.cycle.failed',{code:error.code,message:error.message});}await delay(Number(config.pollIntervalMs||15000));}}

main().catch(error=>{log('agent.fatal',{message:error.message});process.exitCode=1;});
