const fs=require('node:fs');
const path=require('node:path');
const https=require('node:https');
const net=require('node:net');
const {execFile}=require('node:child_process');
const {createHmac,timingSafeEqual}=require('node:crypto');
const WebSocket=require('ws');

const VERSION='0.1.3-lab.4';
const root=path.dirname(process.execPath);
const bootstrapPath=path.join(root,'bootstrap.json');
const identityPath=path.join(root,'identity.json');
const guestIpCachePath=path.join(root,'guest-ip-cache.json');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const log=(event,detail={})=>process.stdout.write(`${JSON.stringify({time:new Date().toISOString(),event,...detail})}\n`);
const readJson=file=>JSON.parse(fs.readFileSync(file,'utf8').replace(/^\uFEFF/,''));
const writePrivate=(file,value)=>{fs.writeFileSync(file,JSON.stringify(value,null,2),{encoding:'utf8',mode:0o600});};
const run=(file,args,timeout=30000)=>new Promise((resolve,reject)=>execFile(file,args,{windowsHide:true,timeout},(error,stdout,stderr)=>error?reject(Object.assign(error,{detail:String(stderr||stdout).trim()})):resolve(String(stdout))));

function request(config,method,pathname,body,headers={}){
  const base=new URL(config.apiUrl),payload=body===undefined?null:Buffer.from(JSON.stringify(body));
  const ca=config.caCertificatePath?fs.readFileSync(config.caCertificatePath):undefined;
  return new Promise((resolve,reject)=>{const req=https.request({protocol:base.protocol,hostname:base.hostname,port:base.port||443,path:`${base.pathname.replace(/\/$/,'')}${pathname}`,method,ca,rejectUnauthorized:true,headers:{accept:'application/json',...(payload?{'content-type':'application/json','content-length':payload.length}:{}),...headers}},res=>{let raw='';res.setEncoding('utf8');res.on('data',chunk=>raw+=chunk);res.on('end',()=>{let parsed={};try{parsed=raw?JSON.parse(raw):{};}catch{return reject(new Error(`Invalid JSON response (${res.statusCode}).`));}if(res.statusCode<200||res.statusCode>=300)return reject(Object.assign(new Error(parsed.detail||`HTTP ${res.statusCode}`),{code:parsed.code,status:res.statusCode}));resolve(parsed);});});req.setTimeout(30000,()=>req.destroy(new Error('Nuvrion request timed out.')));req.on('error',reject);if(payload)req.write(payload);req.end();});
}
function walkVmx(rootPath,result,depth=0){if(depth>8||result.length>=2000||!fs.existsSync(rootPath))return;let entries=[];try{entries=fs.readdirSync(rootPath,{withFileTypes:true});}catch{return;}for(const entry of entries){const full=path.join(rootPath,entry.name);if(entry.isDirectory())walkVmx(full,result,depth+1);else if(entry.isFile()&&entry.name.toLowerCase().endsWith('.vmx'))result.push(full);}}
function vmxValue(text,key){const match=text.match(new RegExp(`^\\s*${key}\\s*=\\s*"([^"]*)"`,'mi'));return match?match[1]:null;}
function consolePassword(secret,vmxPath){return createHmac('sha256',secret).update(`nuvrion-workstation-console\0${String(vmxPath).replaceAll('\\','/').toLowerCase()}`).digest('hex').slice(0,8);}
function consoleRange(config){const start=Number(config.consolePortRange?.start??5900),end=Number(config.consolePortRange?.end??5999);if(!Number.isInteger(start)||!Number.isInteger(end)||start<1024||end>65535||start>end||end-start>999)throw Object.assign(new Error('consolePortRange must contain a valid range of at most 1000 ports.'),{code:'NUV_AGENT_CONSOLE_RANGE_INVALID'});return {start,end};}
function setVmxValue(text,name,value){const pattern=new RegExp(`^\\s*${name.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')}\\s*=\\s*"[^"]*"\\s*$`,'mi'),line=`${name} = "${value}"`;if(pattern.test(text))return text.replace(pattern,line);const newline=text.includes('\r\n')?'\r\n':'\n';return `${text.trimEnd()}${newline}${line}${newline}`;}
function writeVmx(file,text){const temporary=`${file}.nuvrion.tmp`;fs.writeFileSync(temporary,text,{encoding:'utf8',mode:fs.statSync(file).mode});fs.renameSync(temporary,file);}
function reconcileConsoleConfiguration(config,files,running){if(config.autoConfigureConsole===false)return;const range=consoleRange(config),reserved=new Map();for(const file of files){let text='';try{text=fs.readFileSync(file,'utf8');}catch{continue}const port=Number(vmxValue(text,'RemoteDisplay.vnc.port'));if(Number.isInteger(port)&&port>=range.start&&port<=range.end&&!reserved.has(port))reserved.set(port,file.toLowerCase());}for(const file of [...files].sort((a,b)=>a.localeCompare(b))){if(running.has(file.toLowerCase()))continue;let text;try{text=fs.readFileSync(file,'utf8');}catch{continue}const expected=consolePassword(config.identity.secret,file),enabled=/^\s*RemoteDisplay\.vnc\.enabled\s*=\s*"TRUE"/mi.test(text),managed=vmxValue(text,'RemoteDisplay.vnc.password')===expected,current=Number(vmxValue(text,'RemoteDisplay.vnc.port'));if(enabled&&managed&&Number.isInteger(current)&&current>=range.start&&current<=range.end)continue;let port=Number.isInteger(current)&&current>=range.start&&current<=range.end&&(reserved.get(current)===file.toLowerCase()||!reserved.has(current))?current:null;if(!port)for(let candidate=range.start;candidate<=range.end;candidate++)if(!reserved.has(candidate)){port=candidate;break}if(!port){log('agent.console.range_exhausted',{vmxPath:file});continue}reserved.set(port,file.toLowerCase());text=setVmxValue(text,'RemoteDisplay.vnc.enabled','TRUE');text=setVmxValue(text,'RemoteDisplay.vnc.port',String(port));text=setVmxValue(text,'RemoteDisplay.vnc.password',expected);text=setVmxValue(text,'RemoteDisplay.vnc.ip','127.0.0.1');writeVmx(file,text);log('agent.console.configured',{vmxPath:file,port});}}
async function mapLimit(items,limit,mapper){const results=new Array(items.length);let next=0;async function worker(){for(;;){const index=next++;if(index>=items.length)return;results[index]=await mapper(items[index],index);}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return results;}
async function guestIpAddress(config,file,powerState,cache){const key=file.toLowerCase();if(powerState==='running'){try{const output=await run(config.vmrunPath,['getGuestIPAddress',file],5000),address=output.split(/\s+/).map(value=>value.trim()).find(value=>net.isIP(value));if(address){cache[key]=address;return address;}}catch{/* VMware Tools may not be ready or installed */}}return net.isIP(cache[key])?cache[key]:null;}
async function inventory(config){const runningOutput=await run(config.vmrunPath,['list']),running=new Set(runningOutput.split(/\r?\n/).slice(1).map(x=>path.normalize(x.trim()).toLowerCase()).filter(Boolean)),files=[];for(const searchRoot of config.vmSearchRoots||[])walkVmx(searchRoot,files);const unique=[...new Set(files.map(path.normalize))];reconcileConsoleConfiguration(config,unique,running);let cache={};try{cache=readJson(guestIpCachePath);}catch{}const items=await mapLimit(unique,4,async file=>{let text='',readable=true;try{text=fs.readFileSync(file,'utf8');}catch{readable=false}const memory=Number(vmxValue(text,'memsize')),cpu=Number(vmxValue(text,'numvcpus')),port=Number(vmxValue(text,'RemoteDisplay.vnc.port')),enabled=/^\s*RemoteDisplay\.vnc\.enabled\s*=\s*"TRUE"/mi.test(text),managed=vmxValue(text,'RemoteDisplay.vnc.password')===consolePassword(config.identity.secret,file),powerState=running.has(file.toLowerCase())?'running':'stopped',consoleReady=enabled&&Number.isInteger(port)&&port>0&&port<=65535,guestIp=await guestIpAddress(config,file,powerState,cache);return {id:file,nativeId:file,name:vmxValue(text,'displayName')||path.basename(file,'.vmx'),path:file,powerState,guestOs:vmxValue(text,'guestOS'),vcpuCount:Number.isFinite(cpu)&&cpu>0?cpu:null,memoryBytes:Number.isFinite(memory)&&memory>0?memory*1048576:null,privateIps:guestIp?[guestIp]:[],healthState:readable&&['running','stopped'].includes(powerState)?'healthy':'warning',consoleState:consoleReady?(managed?'ready':'manual'):(powerState==='running'?'power_cycle_required':'pending'),consoleManaged:consoleReady&&managed,consolePort:consoleReady?port:null,observedAt:new Date().toISOString()};});writePrivate(guestIpCachePath,cache);return items;}
function verify(secret,envelope){const expected=Buffer.from(createHmac('sha256',secret).update(JSON.stringify(envelope.payload)).digest('base64url')),actual=Buffer.from(String(envelope.signature||''));return expected.length===actual.length&&timingSafeEqual(expected,actual);}
function openConsole(config,targetId){let requestData;try{requestData=JSON.parse(targetId);}catch{throw Object.assign(new Error('Console request is malformed.'),{code:'NUV_AGENT_CONSOLE_REQUEST_INVALID'});}const vmxPath=path.normalize(String(requestData.vmxPath||''));if(!vmxPath||!fs.existsSync(vmxPath))throw Object.assign(new Error('The virtual machine configuration was not found.'),{code:'NUV_AGENT_CONSOLE_VM_NOT_FOUND'});const text=fs.readFileSync(vmxPath,'utf8'),enabled=/^\s*RemoteDisplay\.vnc\.enabled\s*=\s*"TRUE"/mi.test(text),port=Number(vmxValue(text,'RemoteDisplay.vnc.port'));if(!enabled||!Number.isInteger(port)||port<1||port>65535)throw Object.assign(new Error('VMware Workstation VNC is not enabled for this VM. Power off the VM, add RemoteDisplay.vnc.enabled = "TRUE" and RemoteDisplay.vnc.port = "5901" to its .vmx file, then start it again.'),{code:'NUV_AGENT_CONSOLE_VNC_DISABLED'});const base=new URL(config.apiUrl),socketUrl=new URL(`${base.pathname.replace(/\/$/,'')}/api/v1/agent-console-sessions/${encodeURIComponent(requestData.sessionId)}/socket`,base);socketUrl.protocol='wss:';const ca=config.caCertificatePath?fs.readFileSync(config.caCertificatePath):undefined;return new Promise((resolve,reject)=>{let settled=false;const local=net.connect({host:'127.0.0.1',port}),remote=new WebSocket(socketUrl,{ca,rejectUnauthorized:true,headers:{'x-agent-id':config.identity.agentId,'x-agent-secret':config.identity.secret},handshakeTimeout:10000});const fail=error=>{local.destroy();remote.close();if(!settled){settled=true;reject(Object.assign(error,{code:error.code||'NUV_AGENT_CONSOLE_CONNECT_FAILED'}));}};local.once('error',fail);remote.once('error',fail);remote.once('open',()=>{if(settled)return;settled=true;local.on('data',data=>remote.readyState===WebSocket.OPEN&&remote.send(data,{binary:true}));remote.on('message',(data,isBinary)=>local.writable&&local.write(isBinary?data:Buffer.from(data)));local.once('close',()=>remote.close());remote.once('close',()=>local.destroy());resolve({code:'NUV_AGENT_CONSOLE_CONNECTED',message:'Workstation VNC console tunnel connected.',port});});});}
async function execute(config,command){const {operation,targetId}=command.payload;if(!verify(config.identity.secret,command))throw Object.assign(new Error('Command signature is invalid.'),{code:'NUV_AGENT_COMMAND_TAMPERED'});if(Date.parse(command.payload.expiresAt)<=Date.now())throw Object.assign(new Error('Command expired.'),{code:'NUV_AGENT_COMMAND_EXPIRED'});if(operation==='console')return openConsole(config,targetId);const action={start:['start',targetId,'nogui'],stop:['stop',targetId,'soft'],restart:['reset',targetId,'soft']}[operation];if(!action)throw Object.assign(new Error('Unsupported operation.'),{code:'NUV_OPERATION_INVALID'});await run(config.vmrunPath,action,120000);return {code:'NUV_AGENT_OPERATION_COMPLETED',message:`VMware Workstation ${operation} completed.`,powerState:operation==='stop'?'stopped':'running'};}
async function main(){if(!fs.existsSync(bootstrapPath))throw new Error(`Missing ${bootstrapPath}`);const config=readJson(bootstrapPath);if(!config.apiUrl?.startsWith('https://'))throw new Error('apiUrl must use HTTPS.');if(!fs.existsSync(config.vmrunPath))throw new Error(`vmrun was not found at ${config.vmrunPath}`);if(!fs.existsSync(config.caCertificatePath))throw new Error(`CA certificate was not found at ${config.caCertificatePath}`);if(fs.existsSync(identityPath))config.identity=readJson(identityPath);else{const enrolled=await request(config,'POST','/api/v1/agents/enroll',{token:config.enrollmentToken,name:config.agentName||require('node:os').hostname(),version:VERSION});config.identity={agentId:enrolled.agentId,secret:enrolled.secret};writePrivate(identityPath,config.identity);delete config.enrollmentToken;writePrivate(bootstrapPath,config);log('agent.enrolled',{agentId:enrolled.agentId});}
  for(;;){try{const items=await inventory(config);await request(config,'POST',`/api/v1/agents/${config.identity.agentId}/heartbeat`,{version:VERSION,inventory:items},{'x-agent-secret':config.identity.secret});const commands=(await request(config,'GET',`/api/v1/agents/${config.identity.agentId}/commands`,undefined,{'x-agent-secret':config.identity.secret})).items||[];for(const command of commands){let status='completed',result;try{result=await execute(config,command);}catch(error){status='failed';result={code:error.code||'NUV_AGENT_EXECUTION_FAILED',message:error.message};}await request(config,'POST',`/api/v1/agents/${config.identity.agentId}/commands/${command.payload.commandId}/ack`,{status,result},{'x-agent-secret':config.identity.secret});}log('agent.heartbeat',{inventoryCount:items.length,commandCount:commands.length});}catch(error){log('agent.cycle.failed',{code:error.code,message:error.message});}await delay(Number(config.pollIntervalMs||15000));}}

module.exports={consolePassword,consoleRange,guestIpAddress,reconcileConsoleConfiguration,vmxValue};
if(require.main===module)main().catch(error=>{log('agent.fatal',{message:error.message});process.exitCode=1;});
