import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {AgentUpgradeService,AgentUpgradeError,verifyUpgradeArtifact} from '../modules/agents/src/agent-upgrade-service.js';
import {PostgresAgentUpgradeService} from '../modules/agents/src/postgres-agent-upgrade-service.js';
const artifact=Buffer.from('signed-workstation-agent-package');
const releaseInput=()=>({version:'1.2.0',artifactUrl:'https://downloads.example.test/nuvrion-agent-1.2.0.msi',sha256:createHash('sha256').update(artifact).digest('hex'),sizeBytes:artifact.length});
test('signed upgrade manifest and artifact checksum verify successfully',()=>{const service=new AgentUpgradeService(),release=service.registerRelease(releaseInput()),deployment=service.stage('agent-1',release.manifest.releaseId),verified=verifyUpgradeArtifact({release:deployment.release,trustedPublicKey:deployment.trustedPublicKey,artifact});assert.equal(verified.verified,true);assert.equal(verified.version,'1.2.0');});
test('tampered manifests and artifact bytes are rejected',()=>{const service=new AgentUpgradeService(),release=service.registerRelease(releaseInput()),deployment=service.stage('agent-1',release.manifest.releaseId),tampered=structuredClone(deployment.release);tampered.manifest.version='9.9.9';assert.throws(()=>verifyUpgradeArtifact({release:tampered,trustedPublicKey:deployment.trustedPublicKey,artifact}),error=>error instanceof AgentUpgradeError&&error.code==='NUV_AGENT_UPGRADE_SIGNATURE_INVALID');assert.throws(()=>verifyUpgradeArtifact({release:deployment.release,trustedPublicKey:deployment.trustedPublicKey,artifact:Buffer.from('wrong')}),error=>['NUV_AGENT_UPGRADE_SIZE_MISMATCH','NUV_AGENT_UPGRADE_CHECKSUM_MISMATCH'].includes(error.code));});
test('deployment records installed and rollback terminal outcomes',()=>{const service=new AgentUpgradeService(),release=service.registerRelease(releaseInput()),installed=service.stage('agent-1',release.manifest.releaseId),rolledBack=service.stage('agent-2',release.manifest.releaseId);service.report('agent-1',installed.deploymentId,{status:'ready'});assert.equal(service.report('agent-1',installed.deploymentId,{status:'installed'}).status,'installed');const result=service.report('agent-2',rolledBack.deploymentId,{status:'rolled_back',rollbackVersion:'1.1.0',detail:{reason:'health check failed'}});assert.equal(result.rollbackVersion,'1.1.0');assert.throws(()=>service.report('agent-2',rolledBack.deploymentId,{status:'installed'}),error=>error.code==='NUV_AGENT_UPGRADE_TERMINAL');});
test('release registration rejects insecure download URLs and malformed digests',()=>{const service=new AgentUpgradeService();assert.throws(()=>service.registerRelease({...releaseInput(),artifactUrl:'http://downloads.example.test/agent.msi'}),/must use HTTPS/);assert.throws(()=>service.registerRelease({...releaseInput(),sha256:'not-a-digest'}),/SHA-256/);});
test('signed manifests identify their signing key and production requires stable keys',()=>{const service=new AgentUpgradeService(),release=service.registerRelease(releaseInput());assert.match(release.manifest.signingKeyId,/^[a-f0-9]{16}$/);assert.throws(()=>new PostgresAgentUpgradeService({},{}),/signing private and public keys are required/);});
