import test from 'node:test';
import assert from 'node:assert/strict';
import {DiscoveryScheduler} from '../modules/inventory/src/discovery-scheduler.js';

test('scheduled discovery synchronizes enabled connections and reconciles from the same observations',async()=>{const calls=[],connection={id:'connection-1',status:'enabled'},observations=[{nativeId:'vm-1'}],scheduler=new DiscoveryScheduler({connections:{async list(){return [connection]},async recordSync(id,count){calls.push(['sync',id,count])}},provider:{async discover(){calls.push(['discover']);return observations}},inventory:{async synchronize(_connection,items){calls.push(['inventory',items]);return {discovered:items.length}}},reconciler:{async reconcileConnection(_connection,items){calls.push(['reconcile',items]);return [{status:'completed'}]}}});const result=await scheduler.run();assert.equal(result[0].status,'completed');assert.deepEqual(calls.map(call=>call[0]),['discover','inventory','sync','reconcile']);});

test('scheduled discovery prevents overlapping runs and isolates connection failures',async()=>{let release,errors=0;const scheduler=new DiscoveryScheduler({connections:{async list(){return [{id:'one',status:'enabled'},{id:'two',status:'enabled'}]},async recordHealth(){errors++}},provider:{async discover(connection){if(connection.id==='one')throw Object.assign(new Error('offline'),{code:'OFFLINE'});await new Promise(resolve=>{release=resolve});return []}},inventory:{async synchronize(){return {discovered:0}}},reconciler:{async reconcileConnection(){return []}}});const first=scheduler.run();while(!release)await new Promise(resolve=>setImmediate(resolve));assert.equal(await scheduler.run(),null);release();const result=await first;assert.equal(result[0].status,'failed');assert.equal(result[1].status,'completed');assert.equal(errors,1);});

test('scheduled discovery retries transient failures with exponential backoff',async()=>{let attempts=0;const delays=[],failures=[],scheduler=new DiscoveryScheduler({connections:{async list(){return [{id:'retry',status:'enabled'}]},async recordFailure(_id,code,delay){failures.push([code,delay])},async recordSync(){}},provider:{async discover(){attempts++;if(attempts<3)throw Object.assign(new Error('temporary outage'),{code:'NUV_PROVIDER_UNAVAILABLE',retryable:true,status:503});return []}},inventory:{async synchronize(){return {discovered:0}}},reconciler:{async reconcileConnection(){return []}},retryBaseMs:10,retryMaxMs:100,sleep:async delay=>delays.push(delay)});const [result]=await scheduler.run();assert.equal(result.status,'completed');assert.equal(result.attempts,3);assert.deepEqual(delays,[10,20]);assert.deepEqual(failures,[['NUV_PROVIDER_UNAVAILABLE',10],['NUV_PROVIDER_UNAVAILABLE',20]]);});

test('scheduled discovery never retries authentication failures',async()=>{let attempts=0;const scheduler=new DiscoveryScheduler({connections:{async list(){return [{id:'auth',status:'enabled'}]},async recordFailure(){}},provider:{async discover(){attempts++;throw Object.assign(new Error('denied'),{code:'NUV_AUTH_FAILED',retryable:true,status:401})}},inventory:{},reconciler:{},sleep:async()=>assert.fail('authentication failure must not sleep or retry')});const [result]=await scheduler.run();assert.equal(result.status,'failed');assert.equal(result.attempts,1);assert.equal(attempts,1);});

test('scheduled discovery records provider metrics after inventory synchronization',async()=>{const observations=[{resourceType:'virtual_machine',nativeId:'vm-1',metrics:{cpuUtilizationPercent:25}}],resources=[{id:'resource-1',nativeId:'vm-1'}],recorded=[];const scheduler=new DiscoveryScheduler({connections:{async list(){return [{id:'connection-1',status:'enabled'}]},async recordSync(){}},provider:{async discover(){return observations}},inventory:{async synchronize(){return {discovered:1}},async list(){return resources}},performance:{async record(connection,items,current){recorded.push({connection,items,current});return 1}},reconciler:{async reconcileConnection(){return []}}});const [result]=await scheduler.run();assert.equal(result.summary.metricsRecorded,1);assert.equal(recorded.length,1);assert.equal(recorded[0].items,observations);assert.equal(recorded[0].current,resources);});
