import test from 'node:test';import assert from 'node:assert/strict';import {AgentRegistry,AgentRegistryError,deriveWorkstationConsolePassword} from '../modules/agents/src/agent-registry.js';import {WorkstationAgentRuntime,AgentRuntimeError} from '../apps/workstation-agent/src/agent-runtime.js';
function enrolled(){const registry=new AgentRegistry(),token=registry.createEnrollmentToken({createdBy:'admin'}),identity=registry.enroll({token:token.token,name:'engineering-laptop'});return {registry,identity};}
test('agent enrollment token is single-use and secrets remain write-only',async()=>{const registry=new AgentRegistry(),token=registry.createEnrollmentToken(),identity=registry.enroll({token:token.token,name:'workstation-01'});assert.equal(registry.list()[0].id,identity.agentId);assert.equal('secret' in registry.list()[0],false);await assert.rejects(async()=>registry.enroll({token:token.token,name:'duplicate'}),error=>error instanceof AgentRegistryError&&error.code==='NUV_AGENT_ENROLLMENT_INVALID');});
test('authenticated heartbeat updates agent inventory without exposing its secret',()=>{const {registry,identity}=enrolled(),agent=registry.heartbeat(identity.agentId,identity.secret,{version:'0.1.1',inventory:[{id:'vm-1'}]});assert.equal(agent.version,'0.1.1');assert.deepEqual(agent.inventory,[{id:'vm-1'}]);assert.equal('secretHash' in agent,false);});
test('signed command executes once and acknowledges a terminal result',async()=>{const {registry,identity}=enrolled(),envelope=registry.createCommand(identity.agentId,{operation:'start',targetId:'vm-1',requestedBy:'operator'}),runtime=new WorkstationAgentRuntime({agentId:identity.agentId,secret:identity.secret,executor:{async execute(operation,target){return {operation,target,powerState:'running'}}}}),result=await runtime.accept(envelope),ack=registry.acknowledge(identity.agentId,identity.secret,result.commandId,result);assert.equal(ack.status,'completed');assert.equal(ack.result.powerState,'running');await assert.rejects(()=>runtime.accept(envelope),error=>error instanceof AgentRuntimeError&&error.code==='NUV_AGENT_COMMAND_REPLAYED');});
test('signed console command carries an opaque one-time tunnel request',async()=>{const {registry,identity}=enrolled(),targetId=JSON.stringify({sessionId:'0f57490c-712b-48f0-b26e-12e157238fbb',vmxPath:'C:\\VMs\\Lab\\Lab.vmx'}),envelope=registry.createCommand(identity.agentId,{operation:'console',targetId,ttlMs:60000}),runtime=new WorkstationAgentRuntime({agentId:identity.agentId,secret:identity.secret,executor:{async execute(operation,target){return {operation,request:JSON.parse(target)}}}}),result=await runtime.accept(envelope);assert.equal(result.status,'completed');assert.equal(result.result.operation,'console');assert.equal(result.result.request.vmxPath,'C:\\VMs\\Lab\\Lab.vmx');});
test('server and agent derive the same path-bound console password without storing it in inventory',()=>{const {registry,identity}=enrolled(),vmxPath='C:\\VMs\\Lab\\Lab.vmx',credential=registry.consoleCredential(identity.agentId,vmxPath);assert.equal(credential.password,deriveWorkstationConsolePassword(identity.secret,vmxPath));assert.match(credential.password,/^[a-f0-9]{8}$/);assert.notEqual(credential.password,deriveWorkstationConsolePassword(identity.secret,'C:\\VMs\\Other\\Other.vmx'));});
test('agent rejects tampered, expired, and wrong-recipient commands',async()=>{const {registry,identity}=enrolled(),envelope=registry.createCommand(identity.agentId,{operation:'stop',targetId:'vm-1',ttlMs:10}),runtime=new WorkstationAgentRuntime({agentId:identity.agentId,secret:identity.secret,clock:()=>Date.parse(envelope.payload.issuedAt),executor:{execute(){}}});const tampered=structuredClone(envelope);tampered.payload.targetId='vm-2';await assert.rejects(()=>runtime.accept(tampered),error=>error.code==='NUV_AGENT_COMMAND_TAMPERED');const wrong=new WorkstationAgentRuntime({agentId:'another-agent',secret:identity.secret,executor:{execute(){}}});await assert.rejects(()=>wrong.accept(envelope),error=>error.code==='NUV_AGENT_COMMAND_WRONG_RECIPIENT');const expired=new WorkstationAgentRuntime({agentId:identity.agentId,secret:identity.secret,clock:()=>Date.parse(envelope.payload.expiresAt)+1,executor:{execute(){}}});await assert.rejects(()=>expired.accept(envelope),error=>error.code==='NUV_AGENT_COMMAND_EXPIRED');});
test('agent secret rotation immediately invalidates the prior secret',()=>{const {registry,identity}=enrolled(),rotated=registry.rotateSecret(identity.agentId);assert.equal(registry.authenticate(identity.agentId,identity.secret),null);assert.equal(registry.authenticate(identity.agentId,rotated.secret).id,identity.agentId);assert.notEqual(rotated.secret,identity.secret);});
test('agent revocation rejects authentication and queued commands',()=>{const {registry,identity}=enrolled(),envelope=registry.createCommand(identity.agentId,{operation:'start',targetId:'vm-1'}),revoked=registry.revoke(identity.agentId,{reason:'device retired'});assert.equal(revoked.status,'revoked');assert.equal(revoked.revocationReason,'device retired');assert.equal(registry.authenticate(identity.agentId,identity.secret),null);assert.equal(registry.command(envelope.payload.commandId).status,'rejected');});
test('maintenance sweep marks stale agents offline and expires queued commands',()=>{const {registry,identity}=enrolled(),envelope=registry.createCommand(identity.agentId,{operation:'start',targetId:'vm-1',ttlMs:10}),now=Date.now()+180000,result=registry.sweep({offlineAfterMs:120000,now});assert.equal(result.offline,1);assert.equal(result.expiredCommands,1);assert.equal(registry.agent(identity.agentId).status,'offline');assert.equal(registry.command(envelope.payload.commandId).result.code,'NUV_AGENT_COMMAND_EXPIRED');});
