import {MockProvider} from './mock/src/mock-provider.js';import {VsphereProvider} from './vmware-vsphere/src/vsphere-provider.js';import {WorkstationProvider} from './vmware-workstation/src/workstation-provider.js';import {WorkstationAgentProvider} from './vmware-workstation-agent/src/workstation-agent-provider.js';import {EsxiProvider} from './vmware-esxi/src/esxi-provider.js';import {AwsEc2Provider} from './aws-ec2/src/aws-ec2-provider.js';import {AzureVmProvider} from './azure-vm/src/azure-vm-provider.js';import {probeSshHostKeyFingerprint,probeTlsCertificateFingerprint,createPinnedFetch} from './tls-trust.js';
export function correlateNestedEsxiHostnames(observations,identities){const byAddress=new Map(identities.filter(identity=>identity?.managementAddress&&identity?.hostName).map(identity=>[String(identity.managementAddress).toLowerCase(),identity]));return observations.map(observation=>{if(observation.providerMetadata?.hostName)return observation;const identity=(observation.attributes?.privateIps??[]).map(address=>byAddress.get(String(address).toLowerCase())).find(Boolean);return identity?{...observation,providerMetadata:{...(observation.providerMetadata??{}),hostName:identity.hostName,hostNameSource:identity.source??'esxi_management_api'}}:observation;});}
export class ProviderRouter{
  constructor({connections,agents=null,mock=new MockProvider(),fetchImpl=fetch}){this.connections=connections;this.agents=agents;this.mock=mock;this.fetchImpl=fetchImpl;this.active=new Map();this.activeMedia=new Set();this.activeSnapshots=new Set();this.activeSettings=new Set();this.hostIdentities=new Map();}
  async #ensureEsxiTrustPins(connection){if(!connection.endpointUri)return;let hostname;try{hostname=new URL(connection.endpointUri).hostname;}catch{return}const patch={};if(!connection.configuration?.tlsCertificateSha256){const fingerprint=await probeTlsCertificateFingerprint(hostname);if(fingerprint)patch.tlsCertificateSha256=fingerprint;}if(!connection.configuration?.sshHostKeySha256){const fingerprint=await probeSshHostKeyFingerprint(hostname);if(fingerprint)patch.sshHostKeySha256=fingerprint;}if(Object.keys(patch).length){connection.configuration={...(connection.configuration??{}),...patch};await this.connections.recordTrustPin?.(connection.id,patch);}}
  async forConnection(connection){if(connection.configuration?.adapter==='mock')return this.mock;if(connection.providerType==='vmware_workstation'&&connection.connectionType==='workstation_agent'){if(!this.agents)throw Object.assign(new Error('Workstation agent registry is unavailable.'),{code:'NUV_AGENT_REGISTRY_UNAVAILABLE'});return new WorkstationAgentProvider({registry:this.agents,agentId:connection.configuration?.agentId,verificationAttempts:Number(connection.configuration?.verificationAttempts??90),verificationIntervalMs:Number(connection.configuration?.verificationIntervalMs??500)});}const credential=await this.connections.resolveCredential(connection.id);let fetchImpl=this.fetchImpl;if(connection.providerType==='vmware_vsphere'&&connection.connectionType==='esxi'){await this.#ensureEsxiTrustPins(connection);if(connection.configuration?.tlsCertificateSha256)fetchImpl=createPinnedFetch(connection.configuration.tlsCertificateSha256);}const options={endpointUri:connection.endpointUri,credential,fetchImpl,timeoutMs:Number(connection.configuration?.timeoutMs??15000)};if(connection.providerType==='vmware_workstation')return new WorkstationProvider(options);if(connection.providerType==='vmware_vsphere'&&connection.connectionType==='esxi')return new EsxiProvider(options);if(connection.providerType==='vmware_vsphere')return new VsphereProvider(options);if(connection.providerType==='aws')return AwsEc2Provider.create({credential,region:connection.configuration?.region,maxWaitTime:Number(connection.configuration?.maxWaitTime??300),endpoint:connection.endpointUri??undefined});if(connection.providerType==='azure')return AzureVmProvider.create({credential,subscriptionId:connection.configuration?.subscriptionId,endpoint:connection.endpointUri??undefined});throw Object.assign(new Error('Provider adapter is unavailable.'),{code:'NUV_PROVIDER_UNAVAILABLE'});}
  async hostIdentity(connection){const cached=this.hostIdentities.get(connection.id);if(cached?.expiresAt>Date.now())return cached.value;const adapter=await this.forConnection(connection);if(!adapter.hostIdentity)return null;const value=await adapter.hostIdentity();this.hostIdentities.set(connection.id,{value,expiresAt:Date.now()+60000});return value;}
  async discover(connection){const observations=await (await this.forConnection(connection)).discover();if(connection.providerType!=='vmware_workstation'||connection.connectionType!=='workstation_agent')return observations;const linked=(await this.connections.list()).filter(candidate=>candidate.status==='enabled'&&candidate.providerType==='vmware_vsphere'&&candidate.connectionType==='esxi'),identities=[];for(const candidate of linked){let address;try{address=new URL(candidate.endpointUri).hostname;}catch{continue}if(!observations.some(item=>(item.attributes?.privateIps??[]).some(ip=>String(ip).toLowerCase()===address.toLowerCase())))continue;try{const identity=await this.hostIdentity(candidate);if(identity)identities.push(identity);}catch{/* ESXi discovery health is reported by its own connection; Workstation inventory must continue */}}return correlateNestedEsxiHostnames(observations,identities);}
  async test(connection){return (await this.forConnection(connection)).testConnection?.()??{status:'healthy',provider:'mock'};}
  async console(connection,nativeId){const adapter=await this.forConnection(connection);if(!adapter.acquireConsole)throw Object.assign(new Error('Embedded console is unavailable for this provider.'),{code:'NUV_CONSOLE_UNSUPPORTED',status:422});return adapter.acquireConsole(nativeId);}
  async media(connection,nativeId){const adapter=await this.forConnection(connection);if(!adapter.listMedia)throw Object.assign(new Error('CD/DVD media control is unavailable for this provider.'),{code:'NUV_MEDIA_UNSUPPORTED',status:422});return adapter.listMedia(nativeId);}
  async browseMedia(connection,input){const adapter=await this.forConnection(connection);if(!adapter.browseMedia)throw Object.assign(new Error('Host-drive media browsing is unavailable for this provider.'),{code:'NUV_MEDIA_BROWSE_UNSUPPORTED',status:422});return adapter.browseMedia(input?.path??null);}
  async mountMedia(connection,nativeId,input){const key=`${connection.id}:${nativeId}`;if(this.activeMedia.has(key))throw Object.assign(new Error('Another CD/DVD media operation is already running for this VM.'),{code:'NUV_MEDIA_OPERATION_IN_PROGRESS',status:409});this.activeMedia.add(key);try{const adapter=await this.forConnection(connection);if(!adapter.mountMedia)throw Object.assign(new Error('Mounting CD/DVD media is unavailable for this provider.'),{code:'NUV_MEDIA_UNSUPPORTED',status:422});return await adapter.mountMedia(nativeId,input);}finally{this.activeMedia.delete(key);}}
  async ejectMedia(connection,nativeId,input){const key=`${connection.id}:${nativeId}`;if(this.activeMedia.has(key))throw Object.assign(new Error('Another CD/DVD media operation is already running for this VM.'),{code:'NUV_MEDIA_OPERATION_IN_PROGRESS',status:409});this.activeMedia.add(key);try{const adapter=await this.forConnection(connection);if(!adapter.ejectMedia)throw Object.assign(new Error('Ejecting CD/DVD media is unavailable for this provider.'),{code:'NUV_MEDIA_UNSUPPORTED',status:422});return await adapter.ejectMedia(nativeId,input);}finally{this.activeMedia.delete(key);}}
  async snapshots(connection,nativeId){const adapter=await this.forConnection(connection);if(!adapter.listSnapshots)throw Object.assign(new Error('VM snapshots are unavailable for this provider.'),{code:'NUV_SNAPSHOT_UNSUPPORTED',status:422});return adapter.listSnapshots(nativeId);}
  async #snapshotMutation(connection,nativeId,method,...args){const key=`${connection.id}:${nativeId}`;if(this.activeSnapshots.has(key))throw Object.assign(new Error('Another snapshot operation is already running for this VM.'),{code:'NUV_SNAPSHOT_OPERATION_IN_PROGRESS',status:409});this.activeSnapshots.add(key);try{const adapter=await this.forConnection(connection);if(!adapter[method])throw Object.assign(new Error('VM snapshots are unavailable for this provider.'),{code:'NUV_SNAPSHOT_UNSUPPORTED',status:422});return await adapter[method](nativeId,...args);}finally{this.activeSnapshots.delete(key);}}
  async createSnapshot(connection,nativeId,input){return this.#snapshotMutation(connection,nativeId,'createSnapshot',input);}
  async revertSnapshot(connection,nativeId,snapshotId){return this.#snapshotMutation(connection,nativeId,'revertSnapshot',snapshotId);}
  async deleteSnapshot(connection,nativeId,snapshotId){return this.#snapshotMutation(connection,nativeId,'deleteSnapshot',snapshotId);}
  async settings(connection,nativeId){const adapter=await this.forConnection(connection);if(!adapter.getSettings)throw Object.assign(new Error('VM settings are unavailable for this provider.'),{code:'NUV_VM_SETTINGS_UNSUPPORTED',status:422});return adapter.getSettings(nativeId);}
  async updateSettings(connection,nativeId,input){const key=`${connection.id}:${nativeId}`;if(this.activeSettings.has(key))throw Object.assign(new Error('Another settings change is already running for this VM.'),{code:'NUV_VM_SETTINGS_IN_PROGRESS',status:409});this.activeSettings.add(key);try{const adapter=await this.forConnection(connection);if(!adapter.updateSettings)throw Object.assign(new Error('VM settings are unavailable for this provider.'),{code:'NUV_VM_SETTINGS_UNSUPPORTED',status:422});return await adapter.updateSettings(nativeId,input);}finally{this.activeSettings.delete(key);}}
  async execute(operation,nativeId,task){const connection=task.connectionId?await this.connections.get(task.connectionId):null;const adapter=connection?await this.forConnection(connection):this.mock;const accepted=await adapter.execute(operation,nativeId);this.active.set(accepted.providerReference,adapter);return accepted;}
  async verify(reference){const adapter=this.active.get(reference)??this.mock;try{return await adapter.verify(reference);}finally{this.active.delete(reference);}}
}
