import {MockProvider} from './mock/src/mock-provider.js';import {VsphereProvider} from './vmware-vsphere/src/vsphere-provider.js';import {WorkstationProvider} from './vmware-workstation/src/workstation-provider.js';import {WorkstationAgentProvider} from './vmware-workstation-agent/src/workstation-agent-provider.js';import {EsxiProvider} from './vmware-esxi/src/esxi-provider.js';import {AwsEc2Provider} from './aws-ec2/src/aws-ec2-provider.js';import {AzureVmProvider} from './azure-vm/src/azure-vm-provider.js';
export class ProviderRouter{
  constructor({connections,agents=null,mock=new MockProvider(),fetchImpl=fetch}){this.connections=connections;this.agents=agents;this.mock=mock;this.fetchImpl=fetchImpl;this.active=new Map();}
  async forConnection(connection){if(connection.configuration?.adapter==='mock')return this.mock;if(connection.providerType==='vmware_workstation'&&connection.connectionType==='workstation_agent'){if(!this.agents)throw Object.assign(new Error('Workstation agent registry is unavailable.'),{code:'NUV_AGENT_REGISTRY_UNAVAILABLE'});return new WorkstationAgentProvider({registry:this.agents,agentId:connection.configuration?.agentId,verificationAttempts:Number(connection.configuration?.verificationAttempts??20),verificationIntervalMs:Number(connection.configuration?.verificationIntervalMs??500)});}const credential=await this.connections.resolveCredential(connection.id),options={endpointUri:connection.endpointUri,credential,fetchImpl:this.fetchImpl,timeoutMs:Number(connection.configuration?.timeoutMs??15000)};if(connection.providerType==='vmware_workstation')return new WorkstationProvider(options);if(connection.providerType==='vmware_vsphere'&&connection.connectionType==='esxi')return new EsxiProvider(options);if(connection.providerType==='vmware_vsphere')return new VsphereProvider(options);if(connection.providerType==='aws')return AwsEc2Provider.create({credential,region:connection.configuration?.region,maxWaitTime:Number(connection.configuration?.maxWaitTime??300),endpoint:connection.endpointUri??undefined});if(connection.providerType==='azure')return AzureVmProvider.create({credential,subscriptionId:connection.configuration?.subscriptionId,endpoint:connection.endpointUri??undefined});throw Object.assign(new Error('Provider adapter is unavailable.'),{code:'NUV_PROVIDER_UNAVAILABLE'});}
  async discover(connection){return (await this.forConnection(connection)).discover();}
  async test(connection){return (await this.forConnection(connection)).testConnection?.()??{status:'healthy',provider:'mock'};}
  async execute(operation,nativeId,task){const connection=task.connectionId?await this.connections.get(task.connectionId):null;const adapter=connection?await this.forConnection(connection):this.mock;const accepted=await adapter.execute(operation,nativeId);this.active.set(accepted.providerReference,adapter);return accepted;}
  async verify(reference){const adapter=this.active.get(reference)??this.mock;try{return await adapter.verify(reference);}finally{this.active.delete(reference);}}
}
