import { randomUUID, createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
export class TaskStore {
  #tasks = new Map(); #keys = new Map(); #outbox = []; #audit = []; #attempts = []; #file;
  constructor({file=null}={}){this.#file=file;if(file&&existsSync(file)){const s=JSON.parse(readFileSync(file,'utf8'));this.#tasks=new Map(s.tasks??[]);this.#keys=new Map(s.keys??[]);this.#outbox=s.outbox??[];this.#audit=s.audit??[];this.#attempts=s.attempts??[];}}
  #persist(){if(!this.#file)return;mkdirSync(dirname(this.#file),{recursive:true});const tmp=`${this.#file}.tmp`;writeFileSync(tmp,JSON.stringify({schemaVersion:1,tasks:[...this.#tasks],keys:[...this.#keys],outbox:this.#outbox,audit:this.#audit,attempts:this.#attempts},null,2),{mode:0o600});renameSync(tmp,this.#file);}
  #auditEvent(action,outcome,task,detail={}){this.#audit.push({id:randomUUID(),occurredAt:new Date().toISOString(),actorType:task.requestedBy?'user':'system',actorId:task.requestedBy?.id??null,actorName:task.requestedBy?.username??null,action,outcome,targetType:task.target.type,targetId:task.target.id,taskId:task.id,correlationId:task.correlationId,detail});}
  create({ operation, targetId, targetType='virtual_machine', providerNativeId=null, connectionId=null, requestedBy=null, correlationId, idempotencyKey }) {
    const hash = createHash('sha256').update(idempotencyKey).digest('hex');
    const existing = this.#keys.get(hash); if (existing) return { task: this.get(existing), created: false };
    const now = new Date().toISOString();
    const task = { id: randomUUID(), operation, status: 'queued', target: { id: targetId, type: targetType }, providerNativeId, connectionId, requestedBy, correlationId, queuedAt: now, startedAt: null, completedAt: null, progress: { current: 0, total: 1, messageCode: 'NUV_TASK_QUEUED' }, result: null, error: null };
    this.#tasks.set(task.id, task); this.#keys.set(hash, task.id); this.#outbox.push({id:randomUUID(),topic:'task.queued',key:task.id,payload:{taskId:task.id},occurredAt:now,publishedAt:null,attempts:0});this.#auditEvent('task.create','succeeded',task,{operation,targetId});this.#persist();return { task: structuredClone(task), created: true };
  }
  list() { return [...this.#tasks.values()].map(value => structuredClone(value)).sort((a,b) => b.queuedAt.localeCompare(a.queuedAt)); }
  get(id) { const v = this.#tasks.get(id); return v ? structuredClone(v) : null; }
  getByIdempotencyKey(idempotencyKey) { const hash=createHash('sha256').update(idempotencyKey).digest('hex');const id=this.#keys.get(hash);return id?this.get(id):null; }
  activeForTarget(targetId) { const task=[...this.#tasks.values()].find(value=>value.target.id===targetId&&['queued','running'].includes(value.status));return task?structuredClone(task):null; }
  claim(workerId='local-worker') { const task = [...this.#tasks.values()].find(x => x.status === 'queued'&&(!x.retryAt||Date.parse(x.retryAt)<=Date.now())); if (!task) return null; task.status='running';task.retryAt=null;task.startedAt=new Date().toISOString();task.lease={workerId,token:randomUUID(),expiresAt:new Date(Date.now()+30_000).toISOString()};const attempt={id:randomUUID(),taskId:task.id,attemptNo:this.#attempts.filter(x=>x.taskId===task.id).length+1,workerId,startedAt:task.startedAt,completedAt:null,outcome:null};this.#attempts.push(attempt);this.#persist();return structuredClone(task); }
  running(id, providerReference) { const t=this.#tasks.get(id); if (t) { t.providerReference=providerReference; t.progress={current:0,total:1,messageCode:'NUV_PROVIDER_ACCEPTED'};this.#persist(); } }
  complete(id, result) { const t=this.#tasks.get(id); if (t) { t.status='completed'; t.completedAt=new Date().toISOString(); t.progress={current:1,total:1,messageCode:'NUV_TASK_COMPLETED'}; t.result=result;delete t.lease;const a=[...this.#attempts].reverse().find(x=>x.taskId===id&&!x.completedAt);if(a){a.completedAt=t.completedAt;a.outcome='completed';}this.#auditEvent('task.complete','succeeded',t,{resultCode:result.code});this.#persist(); } }
  fail(id, error) { const t=this.#tasks.get(id); if (t) { t.status='failed'; t.completedAt=new Date().toISOString(); t.error=error;delete t.lease;const a=[...this.#attempts].reverse().find(x=>x.taskId===id&&!x.completedAt);if(a){a.completedAt=t.completedAt;a.outcome='failed';}this.#auditEvent('task.complete','failed',t,{errorCode:error.code});this.#persist(); } }
  retry(id,error,delayMs){const t=this.#tasks.get(id);if(!t)return;const now=new Date(),due=new Date(now.getTime()+delayMs);t.status='queued';t.retryAt=due.toISOString();t.error=error;t.progress={current:0,total:1,messageCode:'NUV_TASK_RETRY_SCHEDULED'};delete t.lease;const a=[...this.#attempts].reverse().find(x=>x.taskId===id&&!x.completedAt);if(a){a.completedAt=now.toISOString();a.outcome='retry';}this.#outbox.push({id:randomUUID(),topic:'task.queued',key:t.id,payload:{taskId:t.id},occurredAt:due.toISOString(),publishedAt:null,attempts:0});this.#auditEvent('task.retry','scheduled',t,{errorCode:error.code,retryAt:t.retryAt});this.#persist();}
  verificationRequired(id,error){const t=this.#tasks.get(id);if(!t)return;t.status='verification_required';t.completedAt=new Date().toISOString();t.error=error;t.progress={current:0,total:1,messageCode:'NUV_TASK_VERIFICATION_REQUIRED'};delete t.lease;const a=[...this.#attempts].reverse().find(x=>x.taskId===id&&!x.completedAt);if(a){a.completedAt=t.completedAt;a.outcome='verification_required';}this.#auditEvent('task.verification_required','warning',t,{errorCode:error.code});this.#persist();}
  cancel(id,requestedBy=null){const t=this.#tasks.get(id);if(!t)return {ok:false,code:'NUV_TASK_NOT_FOUND'};if(t.status!=='queued')return {ok:false,code:'NUV_TASK_CANCELLATION_UNSAFE',detail:`A ${t.status} task cannot be safely cancelled.`};t.status='cancelled';t.completedAt=new Date().toISOString();t.progress={current:0,total:1,messageCode:'NUV_TASK_CANCELLED'};t.cancelledBy=requestedBy;this.#auditEvent('task.cancel','succeeded',t,{cancelledBy:requestedBy?.id});this.#persist();return {ok:true,task:structuredClone(t)};}
  manualRetry(id,requestedBy=null){const t=this.#tasks.get(id);if(!t)return {ok:false,code:'NUV_TASK_NOT_FOUND'};if(t.status!=='failed')return {ok:false,code:'NUV_TASK_RETRY_UNSAFE',detail:`A ${t.status} task cannot be manually retried.`};t.status='queued';t.completedAt=null;t.startedAt=null;t.retryAt=null;t.error=null;t.progress={current:0,total:1,messageCode:'NUV_TASK_MANUAL_RETRY'};t.manualRetryBy=requestedBy;const now=new Date().toISOString();this.#outbox.push({id:randomUUID(),topic:'task.queued',key:t.id,payload:{taskId:t.id},occurredAt:now,publishedAt:null,attempts:0});this.#auditEvent('task.retry','requested',t,{requestedBy:requestedBy?.id});this.#persist();return {ok:true,task:structuredClone(t)};}
  recoverExpired(now=Date.now()){let count=0;for(const t of this.#tasks.values()){if(t.status==='running'&&t.lease&&Date.parse(t.lease.expiresAt)<=now){t.status='queued';delete t.lease;t.progress={current:0,total:1,messageCode:'NUV_TASK_RECOVERED'};count++;}}if(count)this.#persist();return count;}
  audit({action,outcome,limit=100}={}){return this.#audit.filter(x=>(!action||x.action===action)&&(!outcome||x.outcome===outcome)).slice(-limit).reverse().map(value => structuredClone(value));}
  outbox(){return this.#outbox.map(value => structuredClone(value));}
  pendingOutbox(limit=50){return this.#outbox.filter(value=>!value.publishedAt&&Date.parse(value.occurredAt)<=Date.now()).slice(0,limit).map(value=>structuredClone(value));}
  markOutboxPublished(id){const message=this.#outbox.find(value=>value.id===id);if(message){message.publishedAt=new Date().toISOString();message.attempts++;this.#persist();}}
  attempts(taskId){return this.#attempts.filter(x=>x.taskId===taskId).map(value => structuredClone(value));}
  metrics(){const values=[...this.#tasks.values()];return {tasksTotal:values.length,tasksQueued:values.filter(x=>x.status==='queued').length,tasksRunning:values.filter(x=>x.status==='running').length,tasksCompleted:values.filter(x=>x.status==='completed').length,tasksFailed:values.filter(x=>x.status==='failed').length,auditEvents:this.#audit.length,outboxUnpublished:this.#outbox.filter(x=>!x.publishedAt).length};}
}
