import {createCipheriv,createDecipheriv,createHash,randomBytes} from 'node:crypto';
const derive=value=>createHash('sha256').update(String(value)).digest(),aad=value=>Buffer.from(String(value??''),'utf8');
export class KeyringConfigurationError extends Error{constructor(message){super(message);this.code='NUV_KEYRING_INVALID';}}
export class KeyringCipher{
  constructor({activeKeyId,keys}){const entries=keys instanceof Map?[...keys]:Object.entries(keys??{});if(!activeKeyId||!entries.length)throw new KeyringConfigurationError('An active encryption key and key ring are required.');this.activeKeyId=activeKeyId;this.keys=new Map(entries.map(([id,value])=>[id,derive(value)]));if(!this.keys.has(activeKeyId))throw new KeyringConfigurationError('The active encryption key is not present in the key ring.');}
  encrypt(value,{context='nuvrion:provider-credential'}={}){const nonce=randomBytes(12),cipher=createCipheriv('aes-256-gcm',this.keys.get(this.activeKeyId),nonce);cipher.setAAD(aad(context));const ciphertext=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return {algorithm:'aes-256-gcm',keyId:this.activeKeyId,nonce,ciphertext,tag:cipher.getAuthTag()};}
  decrypt(secret,{context='nuvrion:provider-credential'}={}){if(secret.algorithm&&secret.algorithm!=='aes-256-gcm')throw new Error('NUV_CIPHERTEXT_ALGORITHM_UNSUPPORTED');const key=this.keys.get(secret.keyId);if(!key)throw new Error('NUV_ENCRYPTION_KEY_UNAVAILABLE');const decipher=createDecipheriv('aes-256-gcm',key,secret.nonce);decipher.setAAD(aad(context));decipher.setAuthTag(secret.tag);return JSON.parse(Buffer.concat([decipher.update(secret.ciphertext),decipher.final()]).toString('utf8'));}
}
export function keyringFromEnvironment(env=process.env,{production=env.NUVRION_RUNTIME_PROFILE==='production'}={}){if(env.NUVRION_ENCRYPTION_KEYS){let keys;try{keys=JSON.parse(env.NUVRION_ENCRYPTION_KEYS);}catch{throw new KeyringConfigurationError('NUVRION_ENCRYPTION_KEYS must be valid JSON.');}return new KeyringCipher({activeKeyId:env.NUVRION_ACTIVE_ENCRYPTION_KEY_ID,keys});}if(production)throw new KeyringConfigurationError('Production requires NUVRION_ENCRYPTION_KEYS and NUVRION_ACTIVE_ENCRYPTION_KEY_ID.');return new KeyringCipher({activeKeyId:'local-development-key',keys:{'local-development-key':env.NUVRION_MASTER_KEY??'local-development-key-change-before-production'}});}
