import {createHash} from 'node:crypto';
const hash=value=>createHash('sha256').update(value).digest('hex');
const unquote=value=>value.replace(/^['"]|['"]$/g,'');
function packageIdentity(key){const clean=unquote(key).replace(/\(.+\)$/,'');const index=clean.lastIndexOf('@');if(index<=0)return null;return {name:clean.slice(0,index),version:clean.slice(index+1)};}
export function parsePnpmComponents(lockText){const lines=String(lockText).split(/\r?\n/),components=[];let packages=false,current=null;for(const line of lines){if(line==='packages:'){packages=true;continue;}if(packages&&line==='snapshots:')break;if(!packages)continue;const entry=line.match(/^  (.+):$/);if(entry){const identity=packageIdentity(entry[1]);current=identity?{...identity,integrity:null}:null;if(current)components.push(current);continue;}const integrity=line.match(/^    resolution: \{integrity: ([^,}]+).*/);if(current&&integrity)current.integrity=unquote(integrity[1]);}return components.sort((a,b)=>`${a.name}@${a.version}`.localeCompare(`${b.name}@${b.version}`));}
function integrityHash(value){if(!value)return undefined;const index=value.indexOf('-');if(index<1)return undefined;const algorithm=value.slice(0,index).toUpperCase().replace('SHA','SHA-'),content=value.slice(index+1);return {alg:algorithm,content};}
const purl=(name,version)=>`pkg:npm/${name.startsWith('@')?`%40${name.slice(1).replace('/','%2F')}`:name}@${version}`;
export function createCycloneDxSbom({lockText,packageJson,sourceRevision='uncommitted-workspace',generatedAt=new Date().toISOString()}){const dependencies=parsePnpmComponents(lockText),components=dependencies.map(item=>{const digest=integrityHash(item.integrity);return {type:'library',name:item.name,version:item.version,'bom-ref':purl(item.name,item.version),purl:purl(item.name,item.version),...(digest?{hashes:[digest]}:{})};}),fingerprint=hash(Buffer.from(JSON.stringify(components))),uuid=`${fingerprint.slice(0,8)}-${fingerprint.slice(8,12)}-4${fingerprint.slice(13,16)}-a${fingerprint.slice(17,20)}-${fingerprint.slice(20,32)}`;return {bomFormat:'CycloneDX',specVersion:'1.6',serialNumber:`urn:uuid:${uuid}`,version:1,metadata:{timestamp:generatedAt,component:{type:'application','bom-ref':`pkg:npm/${packageJson.name}@${packageJson.version}`,name:packageJson.name,version:packageJson.version,purl:`pkg:npm/${packageJson.name}@${packageJson.version}`},properties:[{name:'nuvrion:sourceRevision',value:sourceRevision},{name:'nuvrion:productionDependencyFingerprint',value:fingerprint},{name:'nuvrion:lockfileFormat',value:'pnpm-lock.yaml/9.0'}]},components};}
export function verifyCycloneDxSbom({sbom,lockText,packageJson}){const rebuilt=createCycloneDxSbom({lockText,packageJson,sourceRevision:sbom?.metadata?.properties?.find(x=>x.name==='nuvrion:sourceRevision')?.value,generatedAt:sbom?.metadata?.timestamp}),expected=sbom?.metadata?.properties?.find(x=>x.name==='nuvrion:productionDependencyFingerprint')?.value;if(sbom?.bomFormat!=='CycloneDX'||sbom?.specVersion!=='1.6'||expected!==rebuilt.metadata.properties[1].value||JSON.stringify(sbom.components)!==JSON.stringify(rebuilt.components))throw new Error('NUV_SBOM_VERIFICATION_FAILED');return {verified:true,componentCount:rebuilt.components.length,fingerprint:expected};}
